### ISSUE TITLE
Standardise references

### ISSUE THREAD

**Issue by oerc0122** [castep-docs/castep-docs#101]
Currently references are done however the writer of the documentation thought they should be done. This leads to inconsistency when reading certain parts of the documentation.

Styles of references are as follows:

- Links e.g. `documentation/Groundstate/dftd.md` 
  ```markdown
  [J. Chem. Phys. 127, 124108 (2007)](https://doi.org/10.1063/1.2768530)
  ```
- Footnotes, e.g. `documentation/Molecular_Dynamics/basics.md`
  ```markdown
  [^1]
  ...
  [^1]: G. J. Martyna, M. L. Klein, and M. Tuckerman. Nose-hoover chains - the canonical ensemble via continuous dynamics. J. Chem. Phys., 97:2635-2643, 1992.
  ```
- Bibtex, e.g. `documentation/Pseudopotentials/overview.md`
  ```markdown
  [@delta2016]
  ```
- Plain text, e.g. `documentation/DeltaSCF/lin_ex_delta_scf.md`
  ```markdown
  Phys. Rev. B 78, 075441 (2008).
  ```

Recommend switching fully to Bibtex as this leads to a usable source for users to include in own references, possibly provided as a link or page listing all references used in documentation.

**Comment by jryates** [comment]
My plan was to switch everything to bibtex. I only recently found there is a nice plugin which handles this well (which is now enabled in the config) - the refs.bib file is in the root directory.

**Comment by oerc0122** [comment]
Should be completed with #105
