### ISSUE TITLE
Optados - couldn't replicate

### ISSUE THREAD

**Issue by RamunasSavanevskis** [castep-docs/castep-docs#122]
Going through the Optados tutorial (https://github.com/castep-docs/castep-docs/pull/121) there were several results that couldn't be replicated - this was all using identical files as provided

DOS - 
- Fermi energy from DOS was found to be 4.4479eV rather than 5.4109 eV - I think it's a significant enough difference to warrant note
- Band energy was found to be -6.3472 eV rather than the expected 1.3623 eV. 1.27eV was found by using Python to do a basic calculation, and that result is more reasonable - the data in the .dat file is probably fine

pDOS - 
- The graph in pDOS looks completely different 
![image](https://github.com/user-attachments/assets/d71a36c3-1abd-43de-bb5a-223567748b98) - this is the image I got, and adjusting broadening etc. did not help

coreloss - 
- A single hBN_core_edge.dat file is not created - instead multiple .dat files of the different edges are. The actual results seem fine, but I'm not sure if .odi can be changed somehow to put it into a single one like told here (or if this is just because it's an older version)

jDOS - 
- No results to try replicate here, but the Si2.jadaptive.dat file has this at the header  # Column        Data
1        Energy (eV)
2        DOS (electrons per eV)
3        Integrated DOS (electrons)
but only 2 columns are present

I will update this if I come across any other strange results

**Comment by jryates** [comment]
DOS - we think current code is ok.
pDOS - this was due to low k-point sampling.
jdos - the header is misleading, and I logged this as a bug to fix in the optados repo.
